language: python

branches:
  only:
    - master

virtualenv:
  system_site_packages: true

python:
  - "2.7"

install:
  - pip install .

script:
  - py.test
  - flake8 .

notifications:
  slack: prominentedge:9VnNQcaSr6mHKSC2XHwEjkam
